/**
 * Demo-mode Wathq mock. Returns Mugdm's pre-seeded CR data after a
 * realistic network-feel delay. Only invoked when isDemoMode() === true.
 *
 * Values parsed from CrCertificate.pdf + CR extract.png + VAT certificate
 * (100261168778132.pdf). All real — this is Moe's own establishment.
 */
import type { WathqLookupResult } from './client';
import { demoSleep } from '../demo-mode';

// Real values parsed from CrCertificate.pdf + CR extract.png at repo root.
// (Saudi MoC Unified National Number; new system uses this as the CR identity.)
const MUGDM_CR_NUMBER = '7054053868';

const MOCK_DATA: WathqLookupResult = {
  status: 'active',
  vatNumber: '314729836800003', // Real VAT reg — effective 2026-05-01
  data: {
    name_ar: 'مؤسسة محمد محسن مالكي',
    name_en: 'MOHAMMED MOHSEN MALKI Establishment',
    cr_number: MUGDM_CR_NUMBER,
    cr_issuance_date: '2026-04-13',
    cr_expiry_date: '2027-04-12', // next annual confirmation date
    activity_type: 'Systems Integration',
    city: 'Riyadh',
    capital: '1',
    owners: [
      { name: 'MOHAMMED MOHSEN MAHMOOD MALKI', id_number: '1095318315', share: 100 },
    ],
    barcode_url: 'https://ecr.mc.gov.sa/CR/' + MUGDM_CR_NUMBER,
    legal_form: 'Establishment',
    main_activity_code: '620101', // Systems Integration
    sub_activities: [],
    fiscal_year_end: '12-31',
  },
  raw: {
    __mock: true,
    note: 'Generated by mock-client.ts in MUGDM_DEMO_MODE. Sourced from CrCertificate.pdf + CR extract.png. VAT number is still placeholder until VAT cert is provided.',
  },
};

export async function lookupCRMock(crNumber: string): Promise<WathqLookupResult> {
  // Honour shape contract: 10-digit numeric. Mirror real client behaviour.
  const digits = crNumber.replace(/\s/g, '');
  if (!/^\d{10}$/.test(digits)) {
    throw new Error('CR number must be 10 digits');
  }
  await demoSleep(400, 800);
  // Echo the requested CR back so the UI shows what was looked up.
  return {
    ...MOCK_DATA,
    data: { ...MOCK_DATA.data, cr_number: digits },
  };
}

export function isDemoCR(crNumber: string): boolean {
  return crNumber.replace(/\s/g, '') === MUGDM_CR_NUMBER;
}
